services:
  postgres:
    image: postgres:16
    container_name: ecommerce_postgres
    cap_add:
      - SYS_NICE
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: ecommercedb
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./initdb.sql:/docker-entrypoint-initdb.d/initdb.sql
    networks:
      - default

  ecommerce-backend:
    container_name: ecommerce-backend
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - '8080:8080'
    networks:
      - default

networks:
  default:
    name: ecommerce-network

volumes:
  postgres_data: