spring:
  config:
    activate:
      on-profile: dev

  devtools:
    add-properties: true

  datasource:
    url: jdbc:postgresql://localhost:5432/ecommercedb
    username: admin
    password: admin

  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true